  version: "3"
  services: 
    php: 
      image: "php:apache"
      volumes: 
        - "./src:/var/www/html"
      ports: 
        - "8000:80"
    mysql: 
      image: "mysql"
      restart: "always"
      volumes: 
        - "mysql_db:/var/lib/mysql"
      ports: 
        - "3306:3306"
        - "33060:33060"
      environment: 
        MYSQL_ROOT_PASSWORD: "root"
    phpmyadmin: 
      image: "phpmyadmin/phpmyadmin"
      ports: 
        - "8888:80"
      depends_on: 
        - "mysql"
      environment: 
        PMA_HOST: "mysql"
        PMA_USER: "root"
        PMA_PASSWORD: "user"
  volumes: 
    mysql_db: 
